
#---------------------------------------------------------------------------------
# Clear the implicit built in rules
#---------------------------------------------------------------------------------
.SUFFIXES:
#---------------------------------------------------------------------------------
ifeq ($(strip $(DEVKITPRO)),)
$(error "Please set DEVKITPRO in your environment. export DEVKITPRO=<path to>devkitPro")
endif

include $(DEVKITPRO)/wut/share/wut_rules
export	FREETYPE_CFLAGS		:=	`$(DEVKITPRO)/portlibs/ppc/bin/powerpc-eabi-pkg-config --cflags freetype2`
export	FREETYPE_LIBS		:=	`$(DEVKITPRO)/portlibs/ppc/bin/powerpc-eabi-pkg-config --libs freetype2`

#---------------------------------------------------------------------------------
# TARGET is the name of the output
# TARGETDIR is the directory where final binaries (.elf, .rpx, .wuhb) are placed
# BUILD is the directory where object files & intermediate files will be placed
# SOURCES is a list of directories containing source code
# INCLUDES is a list of directories containing extra header files
# META is the directory with the optional .wuhb icon and splash images
#---------------------------------------------------------------------------------
TARGET		:=	dosbox-wiiu
TARGETDIR	:=	executables
BUILD		:=	build_wiiu
META		:=	meta
SOURCES		:=	source source/libgui source/drivers source/drivers/wut \
				source/drivers/wut/shaders \
				source/dosbox source/dosbox/cpu \
				source/dosbox/dos source/dosbox/fpu source/dosbox/gui \
				source/dosbox/hardware source/dosbox/hardware/mame \
				source/dosbox/ints \
				source/dosbox/misc source/dosbox/shell \
				source/sdlshim
DATA		:=	data/images_hd data/fonts data/sounds data/lang
INCLUDES 	:=  source source/dosbox source/dosbox/include source/sdlshim

#---------------------------------------------------------------------------------
# options for code generation
#---------------------------------------------------------------------------------

LOGGING_ENABLED	?=	0

# DOSBOX_WII selects the console flavour of the core (device-prefixed paths,
# messages), shared by Wii and Wii U despite the name. HW_RVL is deliberately
# not defined: it means Wii hardware (libogc).
CFLAGS		=	-g -O3 -Wall $(MACHDEP) $(INCLUDE) $(FREETYPE_CFLAGS) \
				-Wno-strict-aliasing -DWORDS_BIGENDIAN \
				-D__WIIU__ -D__WUT__ -DDOSBOX_WII \
				-DLOGGER_NO_LOG_ALIAS -DLOGGING_ENABLED=$(LOGGING_ENABLED) \
				-ffunction-sections -fdata-sections
CXXFLAGS	=	$(CFLAGS)
LDFLAGS		=	-g $(MACHDEP) $(RPXSPECS) -Wl,-Map,$(notdir $@).map -Wl,--gc-sections

#---------------------------------------------------------------------------------
# any extra libraries we wish to link with
#---------------------------------------------------------------------------------
LIBS	:=	-lsmb2 -liconv -lwut -lmocha -ldvm \
			-lpng -lvorbisidec -logg -lz $(FREETYPE_LIBS)

#---------------------------------------------------------------------------------
# list of directories containing libraries, this must be the top level containing
# include and lib
#---------------------------------------------------------------------------------
LIBDIRS	:= $(PORTLIBS) $(WUT_ROOT) $(WUT_ROOT)/usr

#---------------------------------------------------------------------------------
# no real need to edit anything past this point unless you need to add additional
# rules for different file extensions
#---------------------------------------------------------------------------------
ifneq ($(BUILD),$(notdir $(CURDIR)))
#---------------------------------------------------------------------------------

export OUTPUT	:=	$(CURDIR)/$(TARGETDIR)/$(TARGET)
export VPATH	:=	$(foreach dir,$(SOURCES),$(CURDIR)/$(dir)) \
					$(foreach dir,$(DATA),$(CURDIR)/$(dir))

export DEPSDIR	:=	$(CURDIR)/$(BUILD)

# Icon and splash images are optional: only passed to wuhbtool if present
export WUHB_ASSETS	:=	$(if $(wildcard $(CURDIR)/$(META)/icon.png),--icon=$(CURDIR)/$(META)/icon.png) \
					$(if $(wildcard $(CURDIR)/$(META)/tv_splash.png),--tv-image=$(CURDIR)/$(META)/tv_splash.png) \
					$(if $(wildcard $(CURDIR)/$(META)/drc_splash.png),--drc-image=$(CURDIR)/$(META)/drc_splash.png)

#---------------------------------------------------------------------------------
# automatically build a list of object files for our project
#---------------------------------------------------------------------------------
CFILES		:=	$(foreach dir,$(SOURCES),$(notdir $(wildcard $(dir)/*.c)))
CPPFILES	:=	$(foreach dir,$(SOURCES),$(notdir $(wildcard $(dir)/*.cpp)))
sFILES		:=	$(foreach dir,$(SOURCES),$(notdir $(wildcard $(dir)/*.s)))
SFILES		:=	$(foreach dir,$(SOURCES),$(notdir $(wildcard $(dir)/*.S)))
BINFILES	:=	$(foreach dir,$(DATA),$(notdir $(wildcard $(dir)/*.ttf) \
					$(wildcard $(dir)/*.lang) $(wildcard $(dir)/*.png) \
					$(wildcard $(dir)/*.ogg) $(wildcard $(dir)/*.pcm)))

#---------------------------------------------------------------------------------
# use CXX for linking C++ projects, CC for standard C
#---------------------------------------------------------------------------------
ifeq ($(strip $(CPPFILES)),)
	export LD	:=	$(CC)
else
	export LD	:=	$(CXX)
endif

export OFILES_BIN	:=	$(addsuffix .o,$(BINFILES))
export OFILES_SOURCES := $(CPPFILES:.cpp=.o) $(CFILES:.c=.o) $(sFILES:.s=.o) $(SFILES:.S=.o)
export OFILES := $(OFILES_BIN) $(OFILES_SOURCES)

export HFILES := $(addsuffix .h,$(subst .,_,$(BINFILES)))

#---------------------------------------------------------------------------------
# build a list of include paths
#---------------------------------------------------------------------------------
export INCLUDE	:=	$(foreach dir,$(INCLUDES),-I$(CURDIR)/$(dir)) \
					$(foreach dir,$(LIBDIRS),-I$(dir)/include) \
					-I$(CURDIR)/$(BUILD)

#---------------------------------------------------------------------------------
# build a list of library paths
#---------------------------------------------------------------------------------
export LIBPATHS	:=	$(foreach dir,$(LIBDIRS),-L$(dir)/lib)

.PHONY: $(BUILD) clean

#---------------------------------------------------------------------------------
$(BUILD):
	@[ -d $@ ] || mkdir -p $@
	@[ -d $(TARGETDIR) ] || mkdir -p $(TARGETDIR)
	@$(MAKE) --no-print-directory -C $(BUILD) -f $(CURDIR)/Makefile.wiiu

#---------------------------------------------------------------------------------
clean:
	@echo clean ...
	@rm -fr $(BUILD) $(OUTPUT).elf $(OUTPUT).rpx $(OUTPUT).wuhb

#---------------------------------------------------------------------------------
else

DEPENDS	:=	$(OFILES:.o=.d)

#---------------------------------------------------------------------------------
# main targets
#---------------------------------------------------------------------------------
$(OUTPUT).wuhb: $(OUTPUT).rpx
	@echo packaging $@ ...
	@$(DEVKITPRO)/tools/bin/wuhbtool $< $@ \
		--name="DOSBox Wii U" \
		--short-name="DOSBox" \
		--author="dborth" \
		$(WUHB_ASSETS)

$(OUTPUT).rpx: $(OUTPUT).elf
$(OUTPUT).elf: $(OFILES)

$(OFILES_SOURCES): $(HFILES)
#---------------------------------------------------------------------------------
# imagelist.h: generated array of every compiled-in PNG (guiImageAssets /
# guiImageAssetCount), for GuiImageDataCache::preload(). Follows BINFILES, so
# it always matches this platform's data dirs with nothing to maintain by hand.
#---------------------------------------------------------------------------------
IMAGE_HFILES := $(filter %_png.h,$(HFILES))

imagelist.h : $(IMAGE_HFILES)
	@echo generating $@
	@printf '%s\n' '#pragma once' '#include <stdint.h>' $(foreach h,$(IMAGE_HFILES),'#include "$(h)"') \
		'static const uint8_t * const guiImageAssets[] = {' $(foreach h,$(IMAGE_HFILES),'    $(basename $(h)),') '};' \
		'static const int guiImageAssetCount = (int)(sizeof(guiImageAssets) / sizeof(guiImageAssets[0]));' > $@

$(OFILES_SOURCES) : imagelist.h
#---------------------------------------------------------------------------------
# This rule links in binary data with various extensions
#---------------------------------------------------------------------------------
%.ttf.o %_ttf.h : %.ttf
	@echo $(notdir $<)
	$(bin2o)

%.lang.o %_lang.h : %.lang
	@echo $(notdir $<)
	$(bin2o)

%.png.o %_png.h : %.png
	@echo $(notdir $<)
	$(bin2o)

%.ogg.o %_ogg.h : %.ogg
	@echo $(notdir $<)
	$(bin2o)

%.pcm.o %_pcm.h : %.pcm
	@echo $(notdir $<)
	$(bin2o)

-include $(DEPENDS)

#---------------------------------------------------------------------------------
endif
#---------------------------------------------------------------------------------
